# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

REGION ?= $(shell oc get infrastructure cluster -o jsonpath='{.status.platformStatus.aws.region}' 2>/dev/null)
CLUSTER ?= $(shell oc get infrastructure cluster -o jsonpath='{.status.infrastructureName}' 2>/dev/null)
EXTRA_PLAYBOOK_OPTS ?=

##@ FSx Tasks

.PHONY: build-fsx
build-fsx: ## Create FSx ONTAP filesystem (requires REGION and CLUSTER variables)
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/site.yaml -e aws_region=$(REGION) -e cluster_name=$(CLUSTER) -e @ansible/fsx-ontap-vars.yml

.PHONY: destroy-fsx
destroy-fsx: ## Delete FSx ONTAP resources (requires REGION and CLUSTER variables)
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/site.yaml -e aws_region=$(REGION) -e cluster_name=$(CLUSTER) -e @ansible/fsx-ontap-vars.yml -e delete_resources=true
