# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

EXTRA_PLAYBOOK_OPTS ?=

##@ FSx Tasks

.PHONY: build-fsx
build-fsx: ## Debug VPC lookup (region auto-detected from cluster, override with REGION=us-east-1)
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/site.yaml -e @ansible/vars/fsx-ontap-vars.yml

.PHONY: destroy-fsx
destroy-fsx: ## Delete FSx ONTAP resources (region auto-detected from cluster, override with REGION=us-east-1)
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/site.yaml -e @ansible/vars/fsx-ontap-vars.yml -e delete_resources=true
